language: ruby
services:
  - postgresql
cache:
  npm: true
  bundler: true
rvm:
  - 2.5
node_js:
  - '10'
  - '12'
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - bash ${FOREMAN_PLUGIN_NAME}/script/travis_setup_postgresql_evr.sh
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - cd ${FOREMAN_PLUGIN_NAME}
  - gem install bundler
  - nvm install 10
  - node --version
  - npm version
  - nvm version
  - cd ../foreman
  - echo "gemspec :path => '../${FOREMAN_PLUGIN_NAME}'" > bundler.d/${FOREMAN_PLUGIN_NAME}.local.rb
  - echo "gem 'katello'" > bundler.d/katello.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - cp ../${FOREMAN_PLUGIN_NAME}/.travis.database.yml config/database.yml
  - cat ../${FOREMAN_PLUGIN_NAME}/.travis.database.yml
  - cat config/database.yml
  - bundle install --jobs=3 --retry=3 --without journald development mysql2 console journald
  - npm install
  - bundle exec rake db:create
  - bundle exec rake webpack:compile
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - cd ../foreman
  - bundle exec rake "${FOREMAN_PLUGIN_NAME}:rubocop"
  - bundle exec rake test:${FOREMAN_PLUGIN_NAME}
  - bundle exec rake "plugin:assets:precompile[${FOREMAN_PLUGIN_NAME}]" RAILS_ENV=production
env:
  global:
    - TESTOPTS=-v
    - FOREMAN_PLUGIN_NAME=foreman_rh_cloud
  matrix:
    - FOREMAN_CORE_BRANCH=develop
addons:
  apt:
    sources:
      - sourceline: 'ppa:qpid/released'
    packages:
      - nodejs
      - git
      - libsqlite3-dev
      - zlib1g-dev
      - libvirt-dev
      - libqpid-proton-core10
      - libqpidbroker-dev
      - libqpidbroker2
      - libqpidclient-dev
      - libqpidclient2
      - libqpidcommon-dev
      - libqpidcommon2
      - libqpidmessaging-dev
      - libqpidmessaging2
      - libqpidtypes-dev
      - libqpidtypes1
