# version: "3"
services:
  postgres:
    image: quay.io/jomitsch/postgres-with-evr
    ports: ['5432:5432']
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
    env:
      POSTGRES_USER: foreman
      POSTGRES_PASSWORD: foreman
  foreman:
    image: quay.io/shimshtein/tfm_plugin_test:tfm2.3
    volumes:
      - ../../:/projects/foreman_rh_cloud:Z
    depends_on:
      - "postgres"
