name: Build container
on: [push]

jobs:
  build_test_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build the test container
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: tfm_plugin_test
          tags: ${{ github.ref_name }}
          containerfiles: |
            ./.github/images/Dockerfile
          context: ./.github/images/
      - name: lowercase repo name
        id: lowercase-repo
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}
      - name: Push To Github container registry
        uses: redhat-actions/push-to-registry@v2
        id: push-to-ghcr
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ steps.lowercase-repo.outputs.lowercase }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push-to-ghcr.outputs) }}"
